package com.glinboy.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EmailAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailAllPropertiesEquals(Email expected, Email actual) {
        assertEmailAutoGeneratedPropertiesEquals(expected, actual);
        assertEmailAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailAllUpdatablePropertiesEquals(Email expected, Email actual) {
        assertEmailUpdatableFieldsEquals(expected, actual);
        assertEmailUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailAutoGeneratedPropertiesEquals(Email expected, Email actual) {
        assertThat(actual)
            .as("Verify Email auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailUpdatableFieldsEquals(Email expected, Email actual) {
        assertThat(actual)
            .as("Verify Email relevant properties")
            .satisfies(a -> assertThat(a.getReceiver()).as("check receiver").isEqualTo(expected.getReceiver()))
            .satisfies(a -> assertThat(a.getSubject()).as("check subject").isEqualTo(expected.getSubject()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getEmailType()).as("check emailType").isEqualTo(expected.getEmailType()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailUpdatableRelationshipsEquals(Email expected, Email actual) {
        // empty method
    }
}
