package com.glinboy.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NotificationDataAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationDataAllPropertiesEquals(NotificationData expected, NotificationData actual) {
        assertNotificationDataAutoGeneratedPropertiesEquals(expected, actual);
        assertNotificationDataAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationDataAllUpdatablePropertiesEquals(NotificationData expected, NotificationData actual) {
        assertNotificationDataUpdatableFieldsEquals(expected, actual);
        assertNotificationDataUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationDataAutoGeneratedPropertiesEquals(NotificationData expected, NotificationData actual) {
        assertThat(actual)
            .as("Verify NotificationData auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationDataUpdatableFieldsEquals(NotificationData expected, NotificationData actual) {
        assertThat(actual)
            .as("Verify NotificationData relevant properties")
            .satisfies(a -> assertThat(a.getDataKey()).as("check dataKey").isEqualTo(expected.getDataKey()))
            .satisfies(a -> assertThat(a.getDataValue()).as("check dataValue").isEqualTo(expected.getDataValue()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationDataUpdatableRelationshipsEquals(NotificationData expected, NotificationData actual) {
        assertThat(actual)
            .as("Verify NotificationData relationships")
            .satisfies(a -> assertThat(a.getNotification()).as("check notification").isEqualTo(expected.getNotification()));
    }
}
