package com.glinboy.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ShortMessageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShortMessageAllPropertiesEquals(ShortMessage expected, ShortMessage actual) {
        assertShortMessageAutoGeneratedPropertiesEquals(expected, actual);
        assertShortMessageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShortMessageAllUpdatablePropertiesEquals(ShortMessage expected, ShortMessage actual) {
        assertShortMessageUpdatableFieldsEquals(expected, actual);
        assertShortMessageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShortMessageAutoGeneratedPropertiesEquals(ShortMessage expected, ShortMessage actual) {
        assertThat(expected)
            .as("Verify ShortMessage auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShortMessageUpdatableFieldsEquals(ShortMessage expected, ShortMessage actual) {
        assertThat(expected)
            .as("Verify ShortMessage relevant properties")
            .satisfies(e -> assertThat(e.getPhoneNumber()).as("check phoneNumber").isEqualTo(actual.getPhoneNumber()))
            .satisfies(e -> assertThat(e.getContent()).as("check content").isEqualTo(actual.getContent()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getCreatedAt()).as("check createdAt").isEqualTo(actual.getCreatedAt()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShortMessageUpdatableRelationshipsEquals(ShortMessage expected, ShortMessage actual) {
        // empty method
    }
}
