package com.glinboy.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ShortMessageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShortMessageAllPropertiesEquals(ShortMessage expected, ShortMessage actual) {
        assertShortMessageAutoGeneratedPropertiesEquals(expected, actual);
        assertShortMessageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShortMessageAllUpdatablePropertiesEquals(ShortMessage expected, ShortMessage actual) {
        assertShortMessageUpdatableFieldsEquals(expected, actual);
        assertShortMessageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShortMessageAutoGeneratedPropertiesEquals(ShortMessage expected, ShortMessage actual) {
        assertThat(actual)
            .as("Verify ShortMessage auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShortMessageUpdatableFieldsEquals(ShortMessage expected, ShortMessage actual) {
        assertThat(actual)
            .as("Verify ShortMessage relevant properties")
            .satisfies(a -> assertThat(a.getPhoneNumber()).as("check phoneNumber").isEqualTo(expected.getPhoneNumber()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShortMessageUpdatableRelationshipsEquals(ShortMessage expected, ShortMessage actual) {
        // empty method
    }
}
