package com.glinboy.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TokenAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTokenAllPropertiesEquals(Token expected, Token actual) {
        assertTokenAutoGeneratedPropertiesEquals(expected, actual);
        assertTokenAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTokenAllUpdatablePropertiesEquals(Token expected, Token actual) {
        assertTokenUpdatableFieldsEquals(expected, actual);
        assertTokenUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTokenAutoGeneratedPropertiesEquals(Token expected, Token actual) {
        assertThat(actual)
            .as("Verify Token auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTokenUpdatableFieldsEquals(Token expected, Token actual) {
        assertThat(actual)
            .as("Verify Token relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getToken()).as("check token").isEqualTo(expected.getToken()))
            .satisfies(a -> assertThat(a.getDisable()).as("check disable").isEqualTo(expected.getDisable()))
            .satisfies(a -> assertThat(a.getDeprecateAt()).as("check deprecateAt").isEqualTo(expected.getDeprecateAt()))
            .satisfies(a -> assertThat(a.getRoles()).as("check roles").isEqualTo(expected.getRoles()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedBy()).as("check updatedBy").isEqualTo(expected.getUpdatedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTokenUpdatableRelationshipsEquals(Token expected, Token actual) {
        // empty method
    }
}
