package com.glinboy.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TokenAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTokenAllPropertiesEquals(Token expected, Token actual) {
        assertTokenAutoGeneratedPropertiesEquals(expected, actual);
        assertTokenAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTokenAllUpdatablePropertiesEquals(Token expected, Token actual) {
        assertTokenUpdatableFieldsEquals(expected, actual);
        assertTokenUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTokenAutoGeneratedPropertiesEquals(Token expected, Token actual) {
        assertThat(expected)
            .as("Verify Token auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTokenUpdatableFieldsEquals(Token expected, Token actual) {
        assertThat(expected)
            .as("Verify Token relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getToken()).as("check token").isEqualTo(actual.getToken()))
            .satisfies(e -> assertThat(e.getDisable()).as("check disable").isEqualTo(actual.getDisable()))
            .satisfies(e -> assertThat(e.getDeprecateAt()).as("check deprecateAt").isEqualTo(actual.getDeprecateAt()))
            .satisfies(e -> assertThat(e.getRoles()).as("check roles").isEqualTo(actual.getRoles()))
            .satisfies(e -> assertThat(e.getCreatedAt()).as("check createdAt").isEqualTo(actual.getCreatedAt()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getUpdatedAt()).as("check updatedAt").isEqualTo(actual.getUpdatedAt()))
            .satisfies(e -> assertThat(e.getUpdatedBy()).as("check updatedBy").isEqualTo(actual.getUpdatedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTokenUpdatableRelationshipsEquals(Token expected, Token actual) {}
}
